apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealm
metadata:
  name: d2-id-k8s-realm-name
spec:
  id: d1-id-kc-realm-name
  realmName: d2-id-kc-realm-name
  keycloakOwner: main
  ssoRealmName: openshift
  ssoRealmEnabled: false # new one
  ssoAutoRedirectEnabled: false # new one
  passwordPolicy:
    - type: "forceExpiredPasswordChange"
      value: "365"
    - type: "length"
      value: "8"
  browserSecurityHeaders:
    "contentSecurityPolicyReportOnly": "ww3",
    "xContentTypeOptions": "ww4",
    "xRobotsTag": "ww5",
    "xFrameOptions": "ww1",
    "contentSecurityPolicy": "ww2",
    "xXSSProtection": "ww6",
    "strictTransportSecurity": "ww7"
  bruteForceProtection:
    enabled: true
    permanentLockout: false
    failureFactor: 1
    quickLoginCheckMilliSeconds: 1
    minimumQuickLoginWaitSeconds: 1
    waitIncrementSeconds: 1
    maxFailureWaitSeconds: 1
    maxDeltaTimeSeconds: 1
  realmEventConfig:
    adminEventsDetailsEnabled: false
    adminEventsEnabled: true
    enabledEventTypes:
      - UPDATE_CONSENT_ERROR
      - CLIENT_LOGIN
    eventsEnabled: true
    eventsExpiration: 15000
    eventsListeners:
      - jboss-logging


